import getRooms from "../getClientRooms";
import RoomStore from "../RoomStore";

import ROOMCODE_LENGTH from "../constants";

/**
 * Removes a client from ALL rooms and notifies participants.
 */
const leaveRooms = client => {
  // Loop through all the rooms the client is in
  getRooms(client).forEach(roomCode => {
    // Only do things if the room code is a 'custom' one ie. not automatically generated by Socket.io on connection
    if (roomCode.length === ROOMCODE_LENGTH) {
      const room = RoomStore.getRoom(roomCode);

      // Let other users know someone left.
      const user = room.getMemberById(client.id);
      if (user) {
        emitLeaveRoom(roomCode, user.nickname);
      }

      // Remove the user from the room's user list.
      delete room.members[client.id];
    }
  });

  client.leaveAll();
};

export default leaveRooms;
