const CREATE_ROOM = 'CREATE_ROOM';
const JOIN_ROOM = 'JOIN_ROOM';
const START = 'START';
const STOP = 'STOP';
const PAUSE = 'PAUSE';
const USER_JOINED = 'USER_JOINED';
const USER_LEFT = 'USER_LEFT';
const MEMBER_LIST = 'MEMBER_LIST';
const NONEXISTANT_ROOM = 'NONEXISTANT_ROOM';
const ROOM_CREATED = 'ROOM_CREATED';
const TIMER_SYNC = 'TIMER_SYNC';

export {
  CREATE_ROOM,
  JOIN_ROOM,
  START,
  STOP,
  PAUSE,
  USER_JOINED,
  USER_LEFT,
  MEMBER_LIST,
  NONEXISTANT_ROOM,
  ROOM_CREATED,
  TIMER_SYNC,
};
