const CREATE_ROOM = 'CREATE_ROOM';
const JOIN_ROOM = 'JOIN_ROOM';
const START = 'START';
const STOP = 'STOP';
const PAUSE = 'PAUSE';
const USER_JOINED = 'USER_JOINED';
const USER_JOINED_SELF = 'USER_JOINED_SELF';
const USER_LEFT = 'USER_LEFT';

export {
  CREATE_ROOM,
  JOIN_ROOM,
  START,
  STOP,
  PAUSE,
  USER_JOINED,
  USER_JOINED_SELF,
  USER_LEFT,
};
