const CREATE_ROOM = 'CREATE_ROOM';
const JOIN_ROOM = 'JOIN_ROOM';
const START = 'START';
const RESET = 'RESET';
const PAUSE = 'PAUSE';
const USER_JOINED = 'USER_JOINED';
const USER_LEFT = 'USER_LEFT';
const MEMBER_LIST = 'MEMBER_LIST';
const NONEXISTANT_ROOM = 'NONEXISTANT_ROOM';
const ROOM_CREATED = 'ROOM_CREATED';
const REQUEST_TIMERS = 'REQUEST_TIMERS';
const TIMER_SYNC = 'TIMER_SYNC';
const GENERIC_MESSAGE = 'GENERIC_MESSAGE';

export {
  CREATE_ROOM,
  JOIN_ROOM,
  START,
  RESET,
  PAUSE,
  USER_JOINED,
  USER_LEFT,
  MEMBER_LIST,
  NONEXISTANT_ROOM,
  ROOM_CREATED,
  REQUEST_TIMERS,
  TIMER_SYNC,
  GENERIC_MESSAGE,
};
