export const CREATE_ROOM = 'CREATE_ROOM';
export const JOIN_ROOM = 'JOIN_ROOM';
export const START = 'START';
export const RESET = 'RESET';
export const PAUSE = 'PAUSE';
export const USER_JOINED = 'USER_JOINED';
export const USER_LEFT = 'USER_LEFT';
export const MEMBER_LIST = 'MEMBER_LIST';
export const NONEXISTANT_ROOM = 'NONEXISTANT_ROOM';
export const ROOM_CREATED = 'ROOM_CREATED';
export const REQUEST_TIMERS = 'REQUEST_TIMERS';
export const TIMER_SYNC = 'TIMER_SYNC';
export const GENERIC_MESSAGE = 'GENERIC_MESSAGE';

export const INT_CONNECTION_ESTABLISHED = 'INT_CONNECTION_ESTABLISHED';
export const INT_CONNECTION_DROPPED = 'INT_CONNECTION_DROPPED';
